// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bklzzmwstpiawfmnbkgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrbHp6bXdzdHBpYXdmbW5ia2dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTEyODAsImV4cCI6MjA2OTg2NzI4MH0.gQjA9Ckir3ggo-G4c3GnwOImvAZMQNu6M4CYI4kSNdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});